MUS3RP0L/virtual-platform-prod

app/Http/Controllers/EconomicComplement/EconomicComplementController.php, app/Http/routes.php, database/migrations/2016_02_02_214425_create_affiliates_table.php, database/migrations/2016_10_19_193528_create_economic_complements_table.php, resources/views/affiliates/view.blade.php
Bug fixes economic complements methods by affiliate
=> Bug fixes database economic complements

resources/views/affiliates/print/legal_action.blade.php, resources/views/affiliates/print/print_debtor_in_contable.blade.php, resources/views/affiliates/print/wallet_arrear.blade.php
=> bug fixes in affiliate Prints

app/Http/Controllers/EconomicComplement/EconomicComplementController.php, resources/views/economic_complements/index.blade.php, resources/views/economic_complements/view.blade.php
=> Ahora si Ale no deberia salirte error  o conflictos

app/Http/Controllers/EconomicComplement/EconomicComplementController.php
=> OrderBy en el procedure

app/AffiliateRecord.php, app/Http/Controllers/EconomicComplement/EconomicComplementController.php, resources/views/economic_complements/index.blade.php
esta mas los  siguientes cambios 
se quito la columna Nua 
se quito búsqueda de % por la izquierda del numero de tramite
=> Corregido el buscador de carnet

app/Http/Controllers/User/UserController.php
=> user edit password  fixed 

app/Http/Controllers/Dashboard/DashboardController.php, app/Http/Controllers/EconomicComplement/EconomicComplementImportExportController.php, app/Http/Controllers/Inbox/InboxController.php, app/Http/Controllers/User/UserController.php
=> correccion en el procedure_id XD

app/Http/Controllers/User/UserController.php
ya funciona ale ya lo probe si puedes hacerle merge y lo presentas eso mas
=> corregido el password ya funciona en admin y no admin

app/Http/Controllers/EconomicComplement/EconomicComplementImportExportController.php
adicionado de columnas en el reporte
=> adicionado las columnas

app/Http/Controllers/EconomicComplement/EconomicComplementController.php, resources/views/affiliates/view.blade.php
se adiciono el estado de las columnas de estado y total al datatables de affiliate view
=> Adicinado columnas de estado y total 

resources/views/affiliates/simple_info.blade.php, resources/views/economic_complements/additional/general_info.blade.php, resources/views/economic_complements/view.blade.php
mostrado de datos en informacion de tramite de complemento economico
=> Cambio View

app/Http/Controllers/EconomicComplement/EconomicComplementImportExportController.php
=> add order by en excel

app/Console/Commands/ExportExcel.php, app/Http/Controllers/ImportAportController.php, app/Http/routes.php, resources/views/app.blade.php
Correccion impresion pdf de observacione y subida de archivo para importar datos de aporte de afiliados Filemaker,Sismu
=> Correccion view app

database/seeds/AddedStateTypeSeeder.php, database/seeds/DatabaseSeeder.php
php artisan db:seed --class=AddedStateTypeSeeder
=> created seeder for add state type

app/Console/Commands/UpdateRequirementsDate.php, app/Console/Kernel.php
=> created command to update requirements

app/Http/Controllers/ImportAportController.php, database/migrations/2017_08_03_083617_addColumnSpouses.php, database/migrations/2017_08_03_085016_addColumnEconApplicant.php
Adicion de columnas en tablas spouses(city_birth_id) eco_com_applicants(date_death, reason_death)
=> add columns migrate

app/Http/Controllers/EconomicComplement/EconomicComplementImportExportController.php, app/Http/routes.php, resources/views/inbox/view.blade.php
adicionado al reporte excel  de complementos XD
=> adicionado el boton de exportacion de complementos

app/Http/Controllers/EconomicComplement/EconomicComplementImportExportController.php
=> Corregido repote excel general

app/Http/Controllers/EconomicComplement/EconomicComplementController.php, resources/views/economic_complements/index.blade.php, resources/views/economic_complements/view.blade.php
tambien se quito el semestre por defecto en el buscador de complementos
=> Terminado historial de documentos tikeados

resources/views/economic_complements/index.blade.php
Hice cambios para ayudar al felix me olvide borrarlos
=> quitando submenu que era de prueba

app/Http/Controllers/Observation/AffiliateObservationController.php
=> adcionando consulta para filtrar tramites 2017

app/Http/Controllers/EconomicComplement/EconomicComplementImportExportController.php, app/Http/routes.php
=> terminado reporte

app/Console/Commands/SearchDegreeChange.php, app/Console/Kernel.php
Comando
php artisan search:degree_change
Nota: se necesita el archivo excel 2016
=> created excel, change degree and category

app/Console/Commands/Exportar_de_MDB.php, app/Helper/Util.php, app/Http/Controllers/Affiliate/AffiliateController.php, app/Http/Controllers/Auth/AuthController.php, app/Http/Controllers/Dashboard/DashboardController.php, app/Http/Controllers/EconomicComplement/EconomicComplementController.php, app/Http/Controllers/User/UserController.php, app/Http/Middleware/RedirectIfAuthenticated.php, app/Http/routes.php, config/database.php, resources/views/auth/change.blade.php, resources/views/economic_complements/view.blade.php, resources/views/partials/mainheader.blade.php
=> Terminado  Amortizacion

app/Http/Controllers/EconomicComplement/EconomicComplementProcedureController.php, database/migrations/2017_09_21_183210_add_columns_bolet.php, resources/views/affiliates/view.blade.php, resources/views/economic_complements/procedure/create.blade.php, resources/views/economic_complements/procedure/index.blade.php, resources/views/economic_complements/view.blade.php
Execute php artisan migrate for create column rent_month on table eco_com_procedures
=> add rent month

app/Http/Controllers/EconomicComplement/EconomicComplementController.php, app/Http/Controllers/EconomicComplement/EconomicComplementImportExportController.php, app/Http/Controllers/Inbox/InboxController.php, app/Providers/AuthServiceProvider.php, resources/views/inbox/view.blade.php
=> corrigiendo bugss  y terminado de envio de tramites a varios 

app/Http/Controllers/EconomicComplement/EconomicComplementController.php, resources/views/economic_complements/view.blade.php
=> boton de devolucion de tramites terminado

resources/views/economic_complements/view.blade.php
=> correccion de errores

app/Http/Controllers/Inbox/InboxController.php, resources/views/inbox/view.blade.php
No deberia existir mas bugs por parte mia en esta vista XD
=> Correccion de bugs knockoutjs en las bandejas

app/EconomicComplementLegalGuardian.php, app/Http/Controllers/EconomicComplement/EconomicComplementController.php, app/Spouse.php, resources/views/affiliates/view.blade.php, resources/views/economic_complements/reception_second_step.blade.php, resources/views/economic_complements/view.blade.php
=> cagaditas del cechus 11

app/Http/Controllers/EconomicComplement/EconomicComplementController.php, resources/views/economic_complements/reception_first_step.blade.php
=> terminado el aps

resources/views/economic_complements/reception_first_step.blade.php
=> renta terminada XD

resources/views/economic_complements/view.blade.php
=> modificacion de devolucion de tramite

app/Console/Commands/ImportDaf.php
=> Change Place

resources/views/inbox/view.blade.php
solo se oculto el boton de envio
=> correccion de bug en los datos iniciales de la bandeja

app/Http/Controllers/EconomicComplement/EconomicComplementController.php
=> cagaditas del cechus v21

app/Http/Controllers/EconomicComplement/EconomicComplementController.php, app/Month.php, database/migrations/2017_11_21_153622_add_mounth_table.php, database/seeds/monthSeeder.php, resources/views/economic_complements/view.blade.php
recacachaditas  del cechus v23
=> Terminado boleta noviembre

app/Http/Controllers/EconomicComplement/EconomicComplementController.php
=> RECONTRARECACACHADITAS DEL CECHUS LA RECACACHO xd

app/Console/Commands/CopyAverage.php, app/Console/Kernel.php
Copy First Semester to Second Semester
=> Copy First Semester to Second Semester

app/Console/Commands/AutomaticCalculation.php
=> Updated calculate automatic

app/Http/Controllers/EconomicComplement/EconomicComplementController.php, app/Http/routes.php, resources/views/economic_complements/index.blade.php
=> Automatic validation

app/Console/Commands/DeleteObservationLoan.php, app/Console/Kernel.php
=> Validation

app/Http/Controllers/EconomicComplement/EconomicComplementImportExportController.php, app/Http/routes.php, resources/views/economic_complements/index.blade.php
=> reporte de amortizados

resources/views/economic_complements/index.blade.php
=> cambiando el nombre hdp

app/Providers/AuthServiceProvider.php
=> rol legal observation

app/Http/Controllers/EconomicComplement/EconomicComplementController.php, resources/views/economic_complements/view.blade.php
=> Edicion de estados

app/Http/Controllers/EconomicComplement/EconomicComplementReportController.php, resources/views/economic_complements/reports/menu.blade.php, resources/views/globalprint/excel_to_pdf.blade.php, resources/views/globalprint/wkhtml.blade.php, storage/excel/imports/.~lock.APS octubre.xlsx#
=> Reporte excel y pdf de derecho hambiente y titulares hdps

app/AffiliateObservation.php, app/Http/Controllers/Affiliate/AffiliateController.php, app/Http/Controllers/EconomicComplement/EconomicComplementController.php, app/Http/Controllers/Observation/AffiliateObservationController.php, app/Http/Controllers/Observation/EconomicComplementObservationController.php, app/Http/routes.php, database/migrations/2018_05_25_114617_AddTypeObservationType.php, resources/views/economic_complements/view.blade.php, resources/views/observations/show_affiliate.blade.php
El cechuz se comio  a la vluna, a karen y tati lo siento brian XD
=> opcion de ver observaciones eliminadas en affiliado y tramite XD

resources/views/affiliates/view.blade.php
=> correccion  de bugs

app/Http/Controllers/EconomicComplement/EconomicComplementController.php, resources/views/economic_complements/reception_first_step.blade.php
=> quitando llenado de rentas

app/Http/Controllers/EconomicComplement/EconomicComplementController.php, resources/views/affiliates/view.blade.php
el cechuz se esta comiendo  a la karerin jajajajajaj
=> comentando edicion de afiliado y corrigiendo edicion de beneficiarios
